specVersion: 1.0.0
name: project1
version: 0.0.5
runner:
  node:
    name: '@subql/node'
    version: '*'
  query:
    name: '@subql/query'
    version: '*'
description: Test Project 1 - how to use SubQuery
repository: 'https://github.com/subquery/shiden-subql-starter'
schema:
  file: ./schema.graphql
network:
  chainId: '0xf1cf9022c7ebb34b162d5b5e34e705a5a740b2d0ecc1009fb89023e62a488108'
  endpoint: 'wss://shiden.api.onfinality.io/public-wss'
  dictionary: 'https://api.subquery.network/sq/subquery/shiden-dictionary'
  chaintypes:
    file: ./dist/chaintypes.js
dataSources:
  - kind: substrate/Runtime
    startBlock: 1
    mapping:
      file: ./dist/index.js
      handlers:
        - handler: handleEvent
          kind: substrate/EventHandler
          filter:
            module: balances
            method: Transfer
